# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# 
# # Function to generate fake data
# def generate_fake_data():
#     money_data = np.random.randint(1000, 10000, size=10)
#     victims_data = np.random.randint(1, 50, size=10)
#     return money_data, victims_data
# 
# # Streamlit app
# st.title("Top Secret Website")
# st.subheader("Enter your credentials to access the data")
# 
# username = st.text_input("Username")
# password = st.text_input("Password", type="password")
# 
# if st.button("Login"):
#     if username and password:
#         st.success(f"Welcome {username}! You've successfully logged in.")
# 
#         money_data, victims_data = generate_fake_data()
# 
#         st.subheader("Current Account Balance (Fake Data)")
#         fig, ax = plt.subplots()
#         ax.bar(range(len(money_data)), money_data, color='green')
#         ax.set_title("Fake Money Data")
#         ax.set_xlabel("Account Number")
#         ax.set_ylabel("Balance ($)")
#         st.pyplot(fig)
# 
#         st.subheader("Victims Convicted (Fake Data)")
#         fig2, ax2 = plt.subplots()
#         ax2.bar(range(len(victims_data)), victims_data, color='red')
#         ax2.set_title("Fake Victims Data")
#         ax2.set_xlabel("Victim Number")
#         ax2.set_ylabel("Number of Victims")
#         st.pyplot(fig2)
#     else:
#         st.error("Please enter both username and password.")
