# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Function to create fake data for graphs
def create_fake_data():
    # Create fake data for money in the current account
    money = np.random.randint(1000, 100000, size=10)
    victims = np.random.randint(1, 100, size=10)
    return money, victims

# Function to display fake graphs
def display_fake_graphs(money, victims):
    st.subheader("Current Account Balance")
    plt.figure(figsize=(10, 5))
    plt.bar(range(len(money)), money, color='green')
    plt.xlabel("Accounts")
    plt.ylabel("Balance ($)")
    plt.title("Fake Graph: Money in Current Accounts")
    st.pyplot(plt)

    st.subheader("Victims Convicted")
    plt.figure(figsize=(10, 5))
    plt.bar(range(len(victims)), victims, color='red')
    plt.xlabel("Cases")
    plt.ylabel("Number of Victims")
    plt.title("Fake Graph: Convicted Victims")
    st.pyplot(plt)

# Streamlit app layout
st.title("Welcome to the Top Secret Website")
st.subheader("Access Restricted Area")

username = st.text_input("Username")
password = st.text_input("Password", type="password")

if st.button("Login"):
    if username and password:
        st.success(f"Welcome {username}! You've successfully logged in.")
        st.write("Accessing top-secret data...")

        # Create and display fake data
        money, victims = create_fake_data()
        display_fake_graphs(money, victims)
    else:
        st.error("Please enter both username and password.")